spring:
  profiles:
    active:
      - prodall
    group:
      prodall:
        - prod
        - prodmq
        - proddb

---
spring.config.activate.on-profile: dev

env: dev

server:
  port: 8080

---
spring.config.activate.on-profile: test

env: test

server:
  port: 8081

---
spring.config.activate.on-profile: prod

env: prod

server:
  port: 8082

---
spring.config.activate.on-profile: proddb

db:
  name: mysql

env: proddb

---
spring.config.activate.on-profile: prodmq

mq:
  address: localhost

env: prodmq